# Generated by Django 5.2 on 2026-10-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_emaillog_options_emaillog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='purpose',
            field=models.CharField(choices=[('others', 'OTHERS'), ('welcome', 'WELCOME'), ('password_reset', 'PASSWORD_RESET'), ('registration', 'REGISTRATION'), ('discount_code', 'DISCOUNT_CODE'), ('otp', 'OTP')], db_index=True, default='others', max_length=50),
        ),
    ]
