name: Dev Branch CI

on:
  push:
    branches: [ dev ]

env:
  # GitHub Secrets
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # GitHub Variables
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}
  DOCKERFILE: ${{ vars.DOCKERFILE }}


jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev
          pip install --upgrade pip
          pip install -r requirements.txt

      #    pip install flake8

      # - name: Lint
      #   run: flake8 .


      - name: Prepare CI env
        run: |
          cp .env.ci.example .env

      # - name: Check migrations
      #   run: python manage.py makemigrations --check --dry-run
      # OR
      - name: Run migrations
        run: |
          python manage.py test


      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: false
          load: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Test Image
        run: |
          docker run --rm \
            --env-file .env \
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
            python manage.py test