name: Django Production CI/CD

on:
  push:
    branches: [ main ]

env:
  # GitHub Secrets
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # GitHub Variables
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}
  DOCKERFILE: ${{ vars.DOCKERFILE }}
  VPS_PROJECT_DIRECTORY: ${{ vars.VPS_PROJECT_DIRECTORY }}
  COMPOSE_FILE: ${{ vars.COMPOSE_FILE }}
  SERVER_IP: ${{ vars.SERVER_IP }}
  SERVER_USER: ${{ vars.SERVER_USER }}
  SERVER_PORT: ${{ vars.SERVER_PORT }}

  # Environment Variables
  MAX_RETRIES: 3
  RETRY_DELAY: 10


jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev
          pip install --upgrade pip
          pip install -r requirements.txt

      #    pip install flake8

      # - name: Lint
      #   run: flake8 .


      - name: Prepare CI env
        run: |
          cp .env.ci.example .env

      - name: Check migrations
        run: python manage.py makemigrations --check --dry-run
      # OR
      # - name: Run migrations
      #   run: |
      #     python manage.py test

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build & Push Image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:latest

      - name: Test Image
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          docker run --rm \
            --env-file .env \
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
            python manage.py test
          

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          port: ${{ env.SERVER_PORT }}
          script: |
            set -e
            cd ${{ env.VPS_PROJECT_DIRECTORY }}
            
            # Remove all existing images for this Docker image
            EXISTING_IMAGES=$(docker images -q ${{ env.DOCKER_IMAGE }})
            if [ -n "$EXISTING_IMAGES" ]; then
                echo "Removing existing images for ${{ env.DOCKER_IMAGE }}..."
                docker rmi -f $EXISTING_IMAGES || true
            fi
            
            # Retry pulling the new image
            COUNT=0
            until docker pull ${{ env.DOCKER_IMAGE }}:${{ github.sha }} || [ $COUNT -eq ${{ env.MAX_RETRIES }} ]; do
                echo "Waiting for image to appear in registry..."
                sleep ${{ env.RETRY_DELAY }}
                COUNT=$((COUNT + 1))
            done
            
            # Restart Docker Compose
            docker compose -f ${{ env.COMPOSE_FILE }} down
            IMAGE_TAG=${{ github.sha }} docker compose -f ${{ env.COMPOSE_FILE }} up -d
